#!/usr/bin/env bash

set -euo pipefail

#
# Bootstrap the DPM Docker integration environment.
#


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

DPM_UID=2000
DPM_GID=2000

CONTAINER_PROPERTIES="$SCRIPT_DIR/config/dpm.properties"
COMMAND_PROPERTIES="$SCRIPT_DIR/config/dpm-command.properties"


CERT_SCRIPT="$ROOT/sbin/dpm-generate-certificates"


if [[ ! -x "$CERT_SCRIPT" ]]; then
    echo "ERROR: certificate generation script is not executable:" >&2
    echo "       $CERT_SCRIPT" >&2
    exit 1
fi

if [[ ! -f "$CONTAINER_PROPERTIES" ]]; then
    echo "ERROR: integration properties file not found:" >&2
    echo "       $CONTAINER_PROPERTIES" >&2
    exit 1
fi

cd "$SCRIPT_DIR"

echo "Stopping existing integration environment..."
sudo docker compose down

echo "Removing old integration certificates..."
rm -rf security

echo "Generating integration certificates..."
#
# The legacy certificate generator creates ./security underneath its
# current working directory, so it must execute from test/integration.
#
"$CERT_SCRIPT"

if [[ ! -f security/ca/cert.pem ||
      ! -f security/admin/cert.pem ||
      ! -f security/admin/key.pem ||
      ! -f security/command/cert.pem ||
      ! -f security/command/key.pem ]]; then
    echo "ERROR: certificate generator did not create the expected security tree." >&2
    exit 1
fi

echo "Setting certificate permissions..."

# Administrative credentials are used by dpmadmin inside the containers.
sudo chgrp "$DPM_GID" security/admin/key.pem
sudo chmod 640 security/admin/key.pem

# Native command programs run as the current host user.
chmod 600 security/command/key.pem

# Certificates themselves need no special protection.
chmod 644 \
    security/ca/cert.pem \
    security/admin/cert.pem \
    security/command/cert.pem

# Apply sensible permissions to JKS files if the generator created them.
if [[ -f security/ca/cert.jks ]]; then
    chmod 644 security/ca/cert.jks
fi

if [[ -f security/admin/key.jks ]]; then
    sudo chgrp "$DPM_GID" security/admin/key.jks
    sudo chmod 640 security/admin/key.jks
fi

echo "Verifying generated certificate key sizes..."
for cert in \
    security/ca/cert.pem \
    security/admin/cert.pem \
    security/command/cert.pem
do
    printf "  %-35s " "$cert"
    openssl x509 -in "$cert" -noout -text |
        sed -n 's/.*Public-Key: (\(.*\))/\1/p' |
        head -1
done

echo "Preparing log directories..."

mkdir -p \
    logs/server \
    logs/agent1

#
# DPM and managed processes run as dpmadmin (UID/GID 2000) in the
# integration containers. Because these are bind mounts, host numeric
# ownership must match the container identity.
#
sudo chown -R "$DPM_UID:$DPM_GID" \
    logs/server \
    logs/agent1

sudo chmod 775 \
    logs/server \
    logs/agent1

echo "Generating host command-client properties..."

#
# Start with the canonical container configuration and make only the
# host/container-specific transformations:
#
#   /etc/dpm/security/... -> test/integration/security/...
#   [master.client] host  -> localhost
#
# Everything else stays identical to config/dpm.properties.
#

tmp_properties="$(mktemp)"

awk -v security="$SCRIPT_DIR/security" '
    BEGIN {
        section = ""
    }

    /^[[:space:]]*\[/ {
        section = $0
    }

    {
        gsub("/etc/dpm/security", security)
    }

    section ~ /^[[:space:]]*\[master\.client\][[:space:]]*$/ &&
    /^[[:space:]]*host[[:space:]]*=/ {
        match($0, /^[[:space:]]*/)
        indent = substr($0, 1, RLENGTH)
        print indent "host = localhost"
        next
    }

    {
        print
    }
' "$CONTAINER_PROPERTIES" > "$tmp_properties"

{
    echo "#"
    echo "# GENERATED FILE -- DO NOT EDIT"
    echo "# Generated by test/integration/bootstrap.sh"
    echo "# Source: config/dpm.properties"
    echo "#"
    cat "$tmp_properties"
} > "$COMMAND_PROPERTIES"

rm -f "$tmp_properties"

echo "Generated:"
echo "  $COMMAND_PROPERTIES"

echo "Building DPM runtime image..."
sudo docker compose build

echo "Starting integration environment..."
sudo docker compose up -d

echo
echo "Integration environment:"
sudo docker compose ps

echo
echo "Host command properties:"
echo "  $COMMAND_PROPERTIES"

echo
echo "Bootstrap complete."
